services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn www.wsgi:application
      --bind 0.0.0.0:8080
      --workers 3
      --timeout 120
      --log-level info
      --access-logfile -
      --error-logfile -
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
      collectstatic:
        condition: service_completed_successfully
    env_file:
      - .env
    restart: always
    volumes:
      - static_volume:/app/staticfiles

  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "python manage.py migrate --noinput"]
    env_file:
      - .env
    restart: "no"

  collectstatic:
    container_name: collectstatic
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "python manage.py collectstatic --noinput --clear"]
    env_file:
      - .env
    restart: "no"
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume:
