services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn www.wsgi:application
      --bind 0.0.0.0:8080
      --workers 3
      --timeout 120
      --log-level info
      --access-logfile -
      --error-logfile -
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    restart: always

  migrate:
    container_name: wapi-migrate
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "python manage.py migrate --noinput"]
    env_file:
      - .env
    restart: "no"
