version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - migration
    restart: unless-stopped
    networks:
      - balance_jar_network

  migration:
    build: .
    env_file:
      - .env
    command: python manage.py migrate
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - balance_jar_network
    restart: "no"

volumes:
  static_volume:
  media_volume:

networks:
  balance_jar_network:
    driver: bridge