# Generated by Django 5.2.7 on 2025-10-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_jar',
            field=models.ForeignKey(blank=True, help_text='Destination jar for transfers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='core.jar'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
