# Generated by Django 5.2.7 on 2025-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_destination_jar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was created', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='jar',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was created', null=True),
        ),
        migrations.AlterField(
            model_name='jar',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was created', null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was created', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was last updated', null=True),
        ),
    ]
